[tool.poetry]
name = "oms-manager"
version = "0.1.0"
description = ""
authors = ["yeangPan <yeangPan@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
